### ISSUE TITLE
Suggestion: Enable the html thing that gives you a pop-up if you try to close a tab on tab groups to make it harder to accidentally delete a tab group by middle-clicking

### ISSUE THREAD

**Issue by ridiche34** [TheNamlessGuy/browser-tab-grouper#10]

**Comment by TheNamlessGuy** [comment]
Good point

**Comment by TheNamlessGuy** [comment]
This should be fixed in the new release (0.4.0). I decided to make it opt-in on a per-group basis though. Perhaps annoying when you first set a group up, but once its done its done.

Mostly because of browser restrictions - you HAVE to interact with the page in some way in order to allow the browser to prompt on close.
This also means that tab groups in reopened windows have to have this value cleared. If it was set previously, you will be warned that it's been unset though.
